diffusion_pretraining: true

continuous: false
atoms_continuous: false
bonds_continuous: false

joint_property_prediction: false

remove_hs: true

use_pos_norm: false

bond_model_guidance: false
bond_prediction: false

seed: 42
# batch_size 40 without adaptive, and 200 with adaptive
batch_size: 4
ema_decay: 0.999
grad_clip_val: 10
accum_batch: 1
gamma: 0.99

use_adaptive_loader: false

gpus: 4
num_epochs: 15
test_interval: 20

#EQGAT
sdim: 256
vdim: 256
edim: 128
num_layers: 12
use_cross_product: false
edge_mp: false
fully_connected: true
local_global_model: false
vector_aggr: mean

#DATA
dataset: enamine
dataset_root: /scratch1/e3moldiffusion/data/enamine/database_noH

# DIFFUSION
additional_feats: false
noise_scheduler: adaptive
loss_weighting: snr_t
eps_min: 1.e-3
beta_min: 1.e-4
beta_max: 2.e-2
timesteps: 500
max_time: 06:00:00:00

#LOGGING
save_dir: /hpfs/userws/cremej01/projects/logs/geom/pretrain_x0
id: 0

#LEARNING
lr_scheduler: reduce_on_plateau
lr: 3.e-4
lr_min: 5.e-5 #used for cyclic scheduler
lr_step_size: 5.e-5 #used for cyclic scheduler
lr_factor: 0.75
lr_patience: 20
max_num_neighbors: 128
weight_decay: 1.e-12

num_workers: 4
precision: 32