#load_ckpt: /scratch1/e3moldiffusion/logs/crossdocked/x0_snr_lr2_bs32_lig_pocket_edges/run0/last-v2.ckpt
# load_ckpt_from_pretrained: /sharedhome/cremej01/workspace/logs/pubchem/x0_pretraining_0_snr_t_weighting_bs400/run0/last.ckpt
#/hpfs/userws/cremej01/projects/logs/pubchem/pretrain_x0_3_adaptive/run0/last.ckpt
# ckpt_bond_model: /hpfs/userws/cremej01/projects/logs/geom/bond_pred_seed1/run0/last.ckpt

remove_hs: true

atoms_continuous: false
bonds_continuous: false
bond_model_guidance: false
bond_prediction: false

#REGRESSION
joint_property_prediction: false
regression_property: [sa_score]

use_pos_norm: false
use_out_norm: false
use_rbfs: true

#LIG-POCKET INTERACTION
ligand_pocket_interaction: true
model_edge-rbf_interaction: true
model_global_edge: true

molsize_loss_weighting: false

seed: 42
batch_size: 8
ema_decay: 0.999
grad_clip_val: 10
accum_batch: 1
gamma: 0.99

use_adaptive_loader: false

gpus: 8
num_epochs: 301
test_interval: 20

#EQGAT
sdim: 256
vdim: 256
edim: 128
num_layers: 12
use_cross_product: false
edge_mp: false
fully_connected: true
local_global_model: false
vector_aggr: mean

#DATA
dataset: crossdocked
dataset_root: /scratch1/cremej01/data/crossdocked_noH_cutoff5_new
dataset_cutoff: 5

# DIFFUSION
additional_feats: false
noise_scheduler: adaptive
loss_weighting: snr_t
eps_min: 1.e-3
beta_min: 1.e-4
beta_max: 2.e-2
timesteps: 500
max_time: 06:00:00:00

#LOGGING
save_dir: /hpfs/userws/cremej01/projects/logs/geom/pretrain_x0
id: 0

#LEARNING
lr_scheduler: reduce_on_plateau
lr: 2.e-4
lr_min: 5.e-5 #used for cyclic scheduler
lr_step_size: 5.e-5 #used for cyclic scheduler
lr_factor: 0.75
lr_patience: 20
max_num_neighbors: 128
weight_decay: 1.e-12

num_workers: 4
precision: 32

#FOR TEST EVAL
save_xyz: true
calculate_energy: true
num_test_graphs: 1000
inference_batch_size: 8
use_ligand_dataset_sizes: true
test_save_dir: /scratch1/e3moldiffusion/logs/crossdocked/test
