# load_ckpt: /hpfs/userws/let55/projects/e3moldiffusion/experiments/geom/logs/x0/newRun/run0/last.ckpt

batch_size: 40
inference_batch_size: 40
ema_decay: 0.999
grad_clip_val: 10
accum_batch: 1
gamma: 0.99

use_adaptive_loader: false
remove_hs: false

gpus: 4
num_epochs: 3000
test_interval: 10

#EQGAT
sdim: 256
vdim: 128
edim: 128
num_layers: 10
use_cross_product: false
local_edge_attrs: false
fully_connected: true
local_global_model: false
vector_aggr: mean

# LATENT
sdim_latent: 128
vdim_latent: 32
edim_latent: 32
num_layers_latent: 8
latent_dim: 128
use_cross_product: false
local_edge_attrs: false
fully_connected: true
local_global_model: false
vector_aggr: mean
vae_beta: 0.05

#DATA
dataset: drugs
dataset_root: /hpfs/userws/let55/projects/e3moldiffusion/experiments/geom/data
# dataset_root: /hpfs/userws/let55/projects/e3moldiffusion/experiments/qm9/data

# DIFFUSION
masked_pretraining: false
continuous: false
schedule: cosine
eps_min: 1.e-3
beta_min: 1.e-4
beta_max: 2.e-2
timesteps: 500
max_time: 06:00:00:00

# save_dir: /hpfs/userws/cremej01/projects/logs/geom/x0
save_dir: /hpfs/userws/let55/projects/e3moldiffusion/experiments/geom/logs/x0/latentdiffusion

lr: 4.e-4
lr_factor: 0.5
lr_patience: 10
max_num_neighbors: 128

weight_decay: 1.e-12

num_workers: 4
precision: 32